language: python

sudo: required

#Pre-install packages for the ubuntu distribution
cache:
  apt: true
  directories:
  - $HOME/.cache/pip
  - $HOME/download

env:
    - NIBABEL=nibabel
    - NIBABEL=git+https://github.com/nipy/nibabel

python:
    - "2.7"
    - "3.6"

before_install:
  - if [ $TRAVIS_PYTHON_VERSION == "2.7" ]; then
        wget http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
        wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - source $HOME/miniconda2/bin/activate root
  - conda update --yes conda

# Install packages
install:
    - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy
    - pip install -r requirements.txt
    - pip install nose
    - pip install codecov
    - pip install $NIBABEL
    - python setup.py build_ext --inplace

# command to run tests
script: 
    - nosetests -v --with-coverage
    - codecov -t 292f41e6-b09f-4d16-b61b-2c4323e77a32
