#!/usr/bin/env python
''' Command Line Interface of extract_parcellation '''
import argparse
from logpar.cli.extract_parcellation import extract_parcellation


if __name__ == "__main__":
    # Parser
    parser = argparse.ArgumentParser(description='Creates dendrogram')

    parser.add_argument('dendrogram', type=str, help='Dendrogram (CSV file)')

    parser.add_argument('nparcels', type=int,
                        help='Number of parcels to extract')

    parser.add_argument('outfile', type=str,
                        help='txt or dlabel.nii file where to write the \
                              resulting parcellation')

    args = parser.parse_args()

    extract_parcellation(args.dendrogram, args.nparcels, args.outfile)
